version: "3.9"
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    ports:
      - "3306:3306"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
