version: "3.9"
services:
  web:
    image: scriptcoded/bth-pattern-g14-web
    restart: always
    ports:
      - "8080:8080"

  api:
    image: scriptcoded/bth-pattern-g14-api
    restart: always
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - SIMULATION_MODE=false
      - API_URL=http://localhost:4000
      - FRONTEND_URL=http://localhost:8080
      - DATABASE_URL=mysql://root:changeme@mysql:3306/pattern
      - REDIS_URL=redis://redis:6379
      - APP_SECRET
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - STRIPE_SECRET_KEY
      - STRIPE_PUBLISHABLE_KEY
      - STRIPE_WEBHOOK_SECRET

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=changeme
    ports:
      # Primarily used for migrations and debugging
      - "3306:3306"
    volumes:
      - mysql-prod-data:/var/lib/mysql

  redis:
    image: redis
    restart: always

volumes:
  mysql-prod-data:
